name: fly.io Deploy
on:
  workflow_run:
    workflows: ["fly.io Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app to fly.io
    runs-on: ubuntu-22.04
    steps:
      - name: Check preview-debug label
        id: check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.eventName === 'workflow_dispatch') {
              core.setOutput('skip', 'false');
            } else {
              const pr = context.payload.workflow_run.pull_requests[0];
              if (!pr) { return core.setFailed('No PR in workflow_run payload'); }
              const { data: labels } = await github.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number
              });
              core.setOutput('skip', labels.some(l => l.name === 'preview-debug').toString());
            }
      - name: Deploy
        if: steps.check.outputs.skip != 'true'
        run: echo "Deploying..."
